import"./assets/styles-JE8YjOlG.js";import{a as u}from"./assets/vendor-N5iQpiFS.js";const e={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),divNotFound:document.querySelector(".not-found"),loadMoreBtn:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),formBtnClearValue:document.querySelector(".search-form__btn-clear"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),modalWishlistBtn:document.querySelector(".modal-product__btn--wishlist"),navCountWishlist:document.querySelector("[data-wishlist-count]")};function E(t){const o=document.querySelectorAll(".categories__btn");Array.from(o).forEach(s=>{s.classList.remove(`${t}`)})}function a(){e.loadMoreBtn.classList.remove("is-hidden")}function g(){e.loadMoreBtn.classList.add("is-hidden")}const n=JSON.parse(localStorage.getItem("wishlist"))||[];function w(t){if(n.includes(t)){const o=n.indexOf(t);n.splice(o,1),localStorage.setItem("wishlist",JSON.stringify(n)),e.modalWishlistBtn.textContent="Add to Wishlist",e.navCountWishlist.textContent=n.length;return}n.push(t),e.modalWishlistBtn.textContent="Remove from Wishlist",console.log(n.length),e.navCountWishlist.textContent=n.length,localStorage.setItem("wishlist",JSON.stringify(n))}function P(){e.modal.classList.remove("modal--is-open")}function A(t){W(t),e.modal.classList.add("modal--is-open")}function W(t){n.includes(t)?e.modalWishlistBtn.textContent="Remove from Wishlist":e.modalWishlistBtn.textContent="Add to Wishlist"}const k="https://dummyjson.com/products",C={CATEGORIES:"/category-list",CATEGORY:"/category",SEARCH:"/search"},d=12;u.defaults.baseURL=k;async function M(){return(await u(`${C.CATEGORIES}`)).data}async function h(t){const o=(t-1)*d,{data:s}=await u(`?limit=${d}&skip=${o}`);return s}async function S(t,o){const s=(o-1)*d,{data:i}=await u(`${C.CATEGORY}/${t}?limit=${d}&skip=${s}`);return i}async function q(t){return(await u(`/${t}`)).data}async function b(t,o){const s=(o-1)*d;return(await u(`${C.SEARCH}?q=${t}&limit=${d}&skip=${s}`)).data}function c(t){const o=t.map(({id:s,thumbnail:i,title:p,brand:_,category:y,price:L})=>`
    <li class="products__item" data-id="${s}">
    <img class="products__image" src="${i}" alt="${p}"/>
    <p class="products__title">${p}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:</span>${_}</p>
    <p class="products__category">Category: ${y}</p>
    <p class="products__price">Price: $${L}</p>
 </li>
 `).join("");e.productsList.insertAdjacentHTML("beforeend",o)}function x(t){const o=t.map(s=>`
    <li class="categories__item">
   <button class="categories__btn" type="button">${s}</button>
 </li>
    `).join("");e.categoriesList.insertAdjacentHTML("beforeend",o)}function v(){e.productsList.innerHTML=""}function O({id:t,thumbnail:o,title:s,tags:i,description:p,shippingInformation:_,returnPolicy:y,price:L}){const B=`
    <img class="modal-product__img" src="${o}" alt="${s}" data-id="${t}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${s}</p >
        <ul class="modal-product__tags">${i.join(", ")}</ul>
        <p class="modal-product__description">${p}</p>
        <p class="modal-product__shipping-information">Shipping: ${_}</p>
        <p class="modal-product__return-policy">Return Policy: ${y}</p>
        <p class="modal-product__price">Price: $${L}</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div >
    `;e.modalProduct.innerHTML=B}let r=1,l="all",$=!1,m=null,f=null;async function I(){e.navCountWishlist.textContent=n.length;try{const{products:t,total:o}=await h(r);c(t),o>12&&a()}catch(t){console.log(t)}try{const t=["all",...await M()];x(t)}catch(t){console.log(t)}}async function N(t){if(r=1,$=!1,t.target.tagName==="BUTTON"){if(v(),g(),e.divNotFound.classList.remove("not-found--visible"),E("categories__btn--active"),t.target.classList.add("categories__btn--active"),l=t.target.textContent,l==="all"){try{const{products:o,total:s}=await h(r);c(o),s>12&&a()}catch(o){console.log(o)}return}try{const{products:o,total:s}=await S(l,r);if(s===0){e.divNotFound.classList.add("not-found--visible");return}c(o),s>12&&a()}catch(o){console.log(o)}}}async function R(){if(r++,g(),l==="all"){try{const{products:t,total:o}=await h(r);c(t),o>12*r&&a()}catch(t){console.log(t)}return}if($){try{const{products:t,total:o}=await b(m,r);c(t),o>12*r&&a()}catch(t){console.log(t)}return}try{const{products:t,total:o}=await S(l,r);c(t),o>12*r&&a()}catch(t){console.log(t)}}async function T(t){if(t.target.closest(".products__item")){f=t.target.closest(".products__item").dataset.id;try{const o=await q(f);O(o),A(f),e.modalCloseBtn.addEventListener("click",P),e.modalWishlistBtn.addEventListener("click",V)}catch(o){console.log(o)}}}async function F(t){if(t.preventDefault(),m=t.target.elements.searchValue.value.trim().toLowerCase(),l=m,!m){alert("Введіть пошукове слово");return}r=1,v(),g(),e.divNotFound.classList.remove("not-found--visible");try{const{products:o,total:s}=await b(m,r);if(s===0){e.divNotFound.classList.add("not-found--visible");return}c(o),s>12&&($=!0,a())}catch(o){console.log(o)}}async function H(){e.searchForm.elements.searchValue.value="",v(),g();try{const{products:t,total:o}=await h(r);c(t),o>12&&a()}catch(t){console.log(t)}}function V(){w(f)}document.addEventListener("DOMContentLoaded",I);e.categoriesList.addEventListener("click",N);e.loadMoreBtn.addEventListener("click",R);e.productsList.addEventListener("click",T);e.searchForm.addEventListener("submit",F);e.formBtnClearValue.addEventListener("click",H);
//# sourceMappingURL=index.js.map
