import"./assets/styles-JE8YjOlG.js";import{a as d}from"./assets/vendor-N5iQpiFS.js";const r={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),divNotFound:document.querySelector(".not-found"),loadMoreBtn:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),formBtnClearValue:document.querySelector(".search-form__btn-clear"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),modalWishlistBtn:document.querySelector(".modal-product__btn--wishlist")};function S(t){const o=document.querySelectorAll(".categories__btn");Array.from(o).forEach(e=>{e.classList.remove(`${t}`)})}function s(){r.loadMoreBtn.classList.remove("is-hidden")}function p(){r.loadMoreBtn.classList.add("is-hidden")}function B(){r.modal.classList.remove("modal--is-open")}function P(){r.modal.classList.add("modal--is-open")}const w="https://dummyjson.com/products",h={CATEGORIES:"/category-list",CATEGORY:"/category",SEARCH:"/search"},l=12;d.defaults.baseURL=w;async function k(){return(await d(`${h.CATEGORIES}`)).data}async function f(t){const o=(t-1)*l,{data:e}=await d(`?limit=${l}&skip=${o}`);return e}async function v(t,o){const e=(o-1)*l,{data:n}=await d(`${h.CATEGORY}/${t}?limit=${l}&skip=${e}`);return n}async function M(t){return(await d(`/${t}`)).data}async function C(t,o){const e=(o-1)*l;return(await d(`${h.SEARCH}?q=${t}&limit=${l}&skip=${e}`)).data}function c(t){const o=t.map(({id:e,thumbnail:n,title:m,brand:_,category:g,price:y})=>`
    <li class="products__item" data-id="${e}">
    <img class="products__image" src="${n}" alt="${m}"/>
    <p class="products__title">${m}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:</span>${_}</p>
    <p class="products__category">Category: ${g}</p>
    <p class="products__price">Price: $${y}</p>
 </li>
 `).join("");r.productsList.insertAdjacentHTML("beforeend",o)}function A(t){const o=t.map(e=>`
    <li class="categories__item">
   <button class="categories__btn" type="button">${e}</button>
 </li>
    `).join("");r.categoriesList.insertAdjacentHTML("beforeend",o)}function L(){r.productsList.innerHTML=""}function q({id:t,thumbnail:o,title:e,tags:n,description:m,shippingInformation:_,returnPolicy:g,price:y}){const E=`
    <img class="modal-product__img" src="${o}" alt="${e}" data-id="${t}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${e}</p >
        <ul class="modal-product__tags">${n.join(", ")}</ul>
        <p class="modal-product__description">${m}</p>
        <p class="modal-product__shipping-information">Shipping: ${_}</p>
        <p class="modal-product__return-policy">Return Policy: ${g}</p>
        <p class="modal-product__price">Price: $${y}</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div >
    `;r.modalProduct.innerHTML=E}let a=1,i="all",$=!1,u=null,b=null;async function T(){try{const{products:t,total:o}=await f(a);c(t),o>12&&s()}catch(t){console.log(t)}try{const t=["all",...await k()];A(t)}catch(t){console.log(t)}}async function R(t){if(a=1,$=!1,t.target.tagName==="BUTTON"){if(L(),p(),r.divNotFound.classList.remove("not-found--visible"),S("categories__btn--active"),t.target.classList.add("categories__btn--active"),i=t.target.textContent,i==="all"){try{const{products:o,total:e}=await f(a);c(o),e>12&&s()}catch(o){console.log(o)}return}try{const{products:o,total:e}=await v(i,a);if(e===0){r.divNotFound.classList.add("not-found--visible");return}c(o),e>12&&s()}catch(o){console.log(o)}}}async function F(){if(a++,p(),i==="all"){try{const{products:t,total:o}=await f(a);c(t),o>12*a&&s()}catch(t){console.log(t)}return}if($){try{const{products:t,total:o}=await C(u,a);c(t),o>12*a&&s()}catch(t){console.log(t)}return}try{const{products:t,total:o}=await v(i,a);c(t),o>12*a&&s()}catch(t){console.log(t)}}async function I(t){if(t.target.closest(".products__item")){b=t.target.closest(".products__item").dataset.id;try{const o=await M(b);q(o),P(),r.modalCloseBtn.addEventListener("click",B),r.modalWishlistBtn.addEventListener("click",onModalWishlistBtnClick)}catch(o){console.log(o)}}}async function N(t){if(t.preventDefault(),u=t.target.elements.searchValue.value.trim().toLowerCase(),i=u,!u){alert("Введіть пошукове слово");return}a=1,L(),p(),r.divNotFound.classList.remove("not-found--visible");try{const{products:o,total:e}=await C(u,a);if(e===0){r.divNotFound.classList.add("not-found--visible");return}c(o),e>12&&($=!0,s())}catch(o){console.log(o)}}async function O(){r.searchForm.elements.searchValue.value="",L(),p();try{const{products:t,total:o}=await f(a);c(t),o>12&&s()}catch(t){console.log(t)}}document.addEventListener("DOMContentLoaded",T);r.categoriesList.addEventListener("click",R);r.loadMoreBtn.addEventListener("click",F);r.productsList.addEventListener("click",I);r.searchForm.addEventListener("submit",N);r.formBtnClearValue.addEventListener("click",O);
//# sourceMappingURL=index.js.map
